EndPoint.Site/Controllers/ClassesController.cs
using AzmoonSaz.Application.Services.Interfaces;
using AzmoonSaz.Common.DTOs.Classroom;
using AzmoonSaz.Common.Enums;
using AzmoonSaz.ViewModels.Classroom;
using AzmoonSaz.ViewModels.User;
using EndPoint.Site.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.Site.Controllers
{
    [Authorize]
    public class ClassesController : Controller
    {
        private readonly IClassroomService _classroomService;
        public ClassesController(IClassroomService classroomService)
        {
            _classroomService = classroomService;
        }


        public async Task<IActionResult> Index()
        {
            var UserId = User.GetUserId();

            var result = await _classroomService.GetUsersClassroomsByUserId(UserId);

            if (result.Status != ServiceStatus.Success)
            {
                ViewBag.Message = result.Message;
                return Redirect("/");
            }


            return View(result.Data
                .Select(c => new ClassroomForListVIewMoldel()
                {
                    ClassId = c.ClassId,
                    ClassName = c.ClassName,
                    IsMyClass = c.IsMyClass
                }));
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(CreateClassroomViewModel classroom)
        {
            if (!ModelState.IsValid)
            {
                return View(classroom);
            }
            var UserId = User.GetUserId();
            RequestCreateClassroomByUserDto request = new RequestCreateClassroomByUserDto()
            {
                ClassName = classroom.ClassName,
                CreatorId = UserId
            };

            var result = await _classroomService.CreateClassroomByUser(request);

            if (result.Status != ServiceStatus.Success)
            {
                ModelState.AddModelError(nameof(CreateClassroomViewModel.ClassName), result.Message);
                return View(classroom);
            }


            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var result = await _classroomService.GetClassroomDetailForEditByUser(Id);

            if (result.Status != ServiceStatus.Success)
            {
                ViewBag.Message = result.Message;

                return RedirectToAction(nameof(Index));
            }
            var model = new EditClassroomViewModel()
            {
                ClassId = result.Data.ClassId,
                Name = result.Data.NewName,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditClassroomViewModel edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            RequestEditClassroomByUserDto request = new RequestEditClassroomByUserDto()
            {
                ClassId = edit.ClassId,
                NewName = edit.Name
            };

            var result = await _classroomService.EditClassroomByUser(request);

            if (result.Status != ServiceStatus.Success)
            {
                ModelState.AddModelError(nameof(EditClassroomViewModel.Name), result.Message);
                return View(edit);
            }


            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Details

        public async Task<IActionResult> Details(int Id = 0)
        {
            if (Id == 0)
            {
                return NotFound();
            }

            var result = await _classroomService.GetStudentsListForClassByClassId(Id);

            if (result.Status != ServiceStatus.Success)
            {
                ViewBag.Message = result.Message;

                return RedirectToAction(nameof(Index));
            }

            ViewBag.ClassName = (await _classroomService.GetClassroomByClassId(Id)).ClassName;
            ViewBag.ClassId = Id;
            return View(result.Data
                .Select(s => new StudentsListForClass()
                {
                    UserId = s.UserId,
                    UserName = s.UserName,
                }));
        }

        #endregion

        #region Delete

        public async Task<IActionResult> Delete(int Id = 0)
        {
            if (Id == 0)
            {
                return NotFound();
            }

            var result = await _classroomService.DeleteClassroomByClassId(Id);

            if (result.Status != ServiceStatus.Success)
            {
                ViewBag.Message = result.Message;
            }

            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

EndPoint.Site/Controllers/TestsController.cs
using AzmoonSaz.Application.Services.Interfaces;
using AzmoonSaz.ViewModels.Tests;
using EndPoint.Site.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.Site.Controllers
{
    public class TestsController : Controller
    {
        private readonly ITestService _testService;
        public TestsController(ITestService testService)
        {
            _testService = testService;
        }

        public async Task<IActionResult> Index()
        {

            int UserId = User.GetUserId();

            var result = await _testService.GetTestsForUserByUserId(UserId);

            return View(result.Data.Select(c => new TestsClassViewModel()
            {
                ClassId = c.ClassId,
                ClassName = c.ClassName,
                IsMyClass = c.IsMyClass,
                Tests = c.Tests.Select(t => new TestsListViewModel()
                {
                    Description = t.Description,
                    Id = t.Id,
                    QuestionsCount = t.QuestionsCount,
                    Title = t.Title
                }).ToList()
            }));
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(int i)
        {
            return View();
        }
    }
}

EndPoint.Site/Views/Tests/Index.cshtml
@model IEnumerable<AzmoonSaz.ViewModels.Tests.TestsClassViewModel>;
@{
    ViewData["Title"] = "آزمونهای من";
}

@foreach (var item in Model)
{
    <article class="home-item m-shadow">
        <h2 class="tests-list-header">کلاس @item.ClassName</h2>
        <span class="tests-list-header">وضعیت :</span>
        @if (item.IsMyClass)
        {
            <span class="btn btn-success tests-list-header">مدیر</span>
        }
        else
        {
            <span class="btn btn-warning tests-list-header">دانش آموز</span>
        }
        ||
        <a asp-action="Details" asp-route-Id="@item.ClassId" asp-controller="Classes" class="btn btn-primary">جزئیات</a>
        <br />
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>عنوان آزمون</th>
                    <th>توضیحات</th>
                    <th>تعداد سوال</th>
                    <th></th>
                <!--
                    asdasd
                    asdasd
                    asdasd
                -->
                </tr>
            </thead>
            <tbody>
                @foreach (var test in item.Tests)
                {
                <tr>
                    <td>@test.Title</td>
                    <td>@test.Description</td>
                    <td>@test.QuestionsCount</td>
                    <td>
                        @*
                        <a href="#" class="btn btn-primary">X</a>
                        <a href="#" class="btn btn-primary">X</a>
                        <a href="#" class="btn btn-primary">X</a>
                        *@
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </article>
}